### ISSUE TITLE
charasay ignores characters after $thoughts when put in variable

### ISSUE THREAD

**Issue by Korbaux** [latipun7/charasay#30]
### Assurance

- [X] I have read and understand the contribution guide, and
- [X] I'm sure there's no relevant issue in this repository

### Current Behavior

Charasay ignores every character after `$thoughts` in variables in chara/cow files

### Steps To Reproduce

1. Run `chara say Hello, World!`
2. Part of the cow's ears are shifted to the left ![image](https://github.com/latipun7/charasay/assets/47117026/9db70fe3-451d-4fb3-b147-d66e4e1b3538)

### Expected Behavior

Charasay should be printing the two spaces after `$thoughts` in chara/cow files

### Other Information

![image](https://github.com/latipun7/charasay/assets/47117026/cd403d3e-f29a-4458-88a3-f2896dd44e82)

**Comment by latipun7** [comment]
Nice catch 😁 I didn't notice it.
Thank you very much ✨
